name: "Windows WSL2 Test"
description: "Reusable windows wsl2 test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect
    - shell: pwsh
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar

    # Yes all this is necessary to get WSL2 working on GitHub Actions without any user input
    # They are all as separate steps so its easier to debug and see what/where it fails (especially when I was writing this)
    - shell: pwsh
      run: |
        dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
        wsl --set-default-version 2
        wsl --update --web-download
        wsl --install --no-distribution
        Invoke-WebRequest -URI https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64-root.tar.xz -OutFile jammy-server-cloudimg-amd64-root.tar.xz
        wsl --import Ubuntu22.04 . jammy-server-cloudimg-amd64-root.tar.xz --version 2
        wsl --list --verbose

    # Install dependencies
    - shell: pwsh
      run: |
        wsl --distribution Ubuntu22.04 --user root -- sudo apt-get update
        wsl --distribution Ubuntu22.04 --user root -- sudo apt-get upgrade -y
        wsl --distribution Ubuntu22.04 --user root -- sudo apt-get install -y openresolv
        wsl --distribution Ubuntu22.04 --user root -- curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
        wsl --distribution Ubuntu22.04 --user root -- sudo bash nodesource_setup.sh
        wsl --distribution Ubuntu22.04 --user root -- sudo apt-get install -y nodejs
        wsl --distribution Ubuntu22.04 --user root -- npm install -g pnpm

    # This is where our testing starts
    - shell: pwsh
      run: |
        wsl --distribution Ubuntu22.04 --user root -- (cd ../ && cp -R ./the-wireguard-effect /tmp)
        wsl --distribution Ubuntu22.04 --user root -- (ls -la /tmp/the-wireguard-effect/)
        wsl --distribution Ubuntu22.04 --user root -- (cd /tmp/the-wireguard-effect && pnpm install)
        wsl --distribution Ubuntu22.04 --user root -- (cd /tmp/the-wireguard-effect && ls -la ./src/)
        wsl --distribution Ubuntu22.04 --user root -- (cd /tmp/the-wireguard-effect && pnpm test -- --run)
