name: "OpenBSD Test"
description: "Reusable openbsd test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar

    - uses: vmactions/openbsd-vm@e6c68b637a12e83519688d115d57d5b0b53923cd # v1.4.6
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg_add sudo-1.9.15.5 node bash
          npm -v
          node -v
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
          pnpm install
          chmod +x ./src/*
          pnpm test
