name: "Linux Test"
description: "Reusable linux test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: "24.x"

    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: sudo apt-get install -y openresolv
    - shell: bash
      run: pnpm install
    - shell: bash
      run: |
        sudo groupadd wireguard-control
        sudo usermod -a -G wireguard-control root
        sudo usermod -a -G wireguard-control runner
        sudo mkdir -p /var/run/wireguard/
        sudo chown -R root:wireguard-control /var/run/wireguard/
        sudo setcap "all=ep" ./submodules/prebuilds/linux-amd64-wireguard-go

    - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
      with:
        timeout_minutes: 1
        retry_wait_seconds: 120
        max_attempts: 3
        shell: bash
        command: pnpm test
