name: "Linux Test"
description: "Reusable linux test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22.x"

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: sudo apt-get install -y openresolv
    - shell: bash
      run: pnpm install
    - shell: bash
      run: |
        sudo groupadd wireguard-control
        sudo usermod -a -G wireguard-control root
        sudo usermod -a -G wireguard-control runner
        sudo mkdir -p /var/run/wireguard/
        sudo chown -R root:wireguard-control /var/run/wireguard/
        sudo setcap "all=ep" ./submodules/prebuilds/linux-amd64-wireguard-go

    - uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
      with:
        timeout_minutes: 1
        retry_wait_seconds: 120
        max_attempts: 3
        shell: bash
        command: pnpm test
