version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "monthly"
#   - package-ecosystem: "gitsubmodule"
#     directory: "/"
#     schedule:
#       interval: "daily"
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"
#   - package-ecosystem: "devcontainers"
#     directory: "/"
#     schedule:
#       interval: "daily"
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     groups:
#       effect:
#         applies-to: version-updates
#         patterns:
#           - "effect"
#           - "@effect*"
#       babel:
#         applies-to: version-updates
#         patterns:
#           - "babel"
#           - "@babel/*"
#       typescript:
#         applies-to: version-updates
#         patterns:
#           - "tsx"
#           - "typescript"
#           - "@typescript-eslint/*"
