stages:
  - build
  - test

variables:
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^renovate\/.+$/i

typescript-build:
  stage: build
  timeout: 10 minutes
  tags:
    - ubuntu-24.04
  artifacts:
    expire_in: 1 week
    paths:
      - /tmp/the-wireguard-effect.tar
  script:
    - sudo apt-get install --yes mingw-w64 libarchive-tools clang cmake libxml2-dev imagemagick librsvg2-bin
    - npm install --global corepack@latest
    - corepack install
    - corepack enable
    - pnpm install

    - pnpm check
    - pnpm lint
    - pnpm circular
    - pnpm build

    - sudo rm -rf .git/
    - sudo rm -rf node_modules/
    - sudo rm -rf submodules/wintun
    - sudo rm -rf submodules/nvlist
    - sudo rm -rf submodules/osxcross
    - sudo rm -rf submodules/wireguard-apple
    - sudo rm -rf submodules/wireguard-go
    - sudo rm -rf submodules/wireguard-tools
    - sudo rm -rf submodules/wireguard-windows
    - tar -cvf /tmp/the-wireguard-effect.tar .
