stages:
  - build
  - test

variables:
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^renovate\/.+$/i

typescript-build:
  stage: build
  timeout: 10 minutes
  tags:
    - ubuntu-24.04
  script:
    - npm install -g corepack@latest
    - corepack install
    - corepack enable
    - pnpm install
    - pnpm check
    - pnpm lint
    - pnpm circular
    - pnpm build
