hoist: false
hoistPattern: []
autoInstallPeers: false
dedupePeerDependents: false
strictPeerDependencies: true

publicHoistPattern:
    - "vitest"
    - "@types/*"
    - "@vitest/*"
    - "@effect/vitest"

allowBuilds:
    esbuild: true
    msgpackr-extract: true

overrides:
    "@effect/docgen>typescript": "7.0.2"
    "madge>typescript": "7.0.2"

peerDependencyRules:
    allowedVersions:
        typescript: "6.0.3"
