name: "MacOSX Intel Test"
description: "Reusable macosx intel test action"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ $(uname -m) != "x86_64" ]]; then
          echo "This job must run on an Apple Intel processor machine"
          exit 1
        fi

    - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22.x"

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - shell: bash
      run: brew install bash
    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: pnpm install
    - uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
      with:
        timeout_minutes: 3
        max_attempts: 3
        shell: bash
        command: sudo -E pnpm test
