name: "MacOSX Apple Silicon Test"
description: "Reusable macosx apple silicon test action"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ $(uname -m) != "arm64" ]]; then
          echo "This job must run on an Apple Silicon machine"
          exit 1
        fi

    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@v4
      with:
        node-version: "22.x"

    - uses: pnpm/action-setup@v4

    - shell: bash
      run: brew install bash
    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: pnpm install
    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 3
        shell: bash
        command: sudo -E pnpm test
