name: "FreeBSD Test"
description: "Reusable freebsd test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg install -y sudo node npm bash
          npm -v
          node -v
          npm install -g pnpm
        run: |
          pnpm install
          chmod +x ./src/*
          kldload linux64
          pnpm test
