name: "FreeBSD Test"
description: "Reusable freebsd test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar

    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg install -y sudo node npm bash
          npm -v
          node -v
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
          pnpm install
          chmod +x ./src/*
          kldload linux64
          pnpm test
