name: "Windows Test"
description: "Reusable windows test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@v4
      with:
        node-version: "18.x"

    - uses: pnpm/action-setup@v4

    - shell: pwsh
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: pwsh
      run: pnpm install

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 3
        shell: pwsh
        command: |
          $env:MSYSTEM = "MINGW64"
          $env:CHERE_INVOKING = "1"
          $env:MSYS2_PATH_TYPE = "inherit"
          C:\msys64\usr\bin\bash.exe -lc "pnpm test"
