name: "Windows Test"
description: "Reusable windows test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect
    - uses: actions/setup-node@v4
      with:
        node-version: "18.x"
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - run: pnpm install
    - run: C:\\msys64\\usr\\bin\\bash.exe -lc "pnpm test"
      env:
        MSYSTEM: "MINGW64"
        CHERE_INVOKING: "1"
        MSYS2_PATH_TYPE: "inherit"
