name: "Windows Test"
description: "Reusable windows test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22.x"

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - shell: pwsh
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: pwsh
      run: pnpm install

    - uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
      with:
        timeout_minutes: 1
        retry_wait_seconds: 120
        max_attempts: 3
        shell: pwsh
        command: |
          $env:MSYSTEM = "MINGW64"
          $env:CHERE_INVOKING = "1"
          $env:MSYS2_PATH_TYPE = "inherit"
          C:\msys64\usr\bin\bash.exe -lc "pnpm test"
