name: "E2E Test"
description: "Reusable e2e test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@v4
      with:
        node-version: "22.x"

    - uses: pnpm/action-setup@v4

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: pnpm install
    - shell: bash
      run: pnpm e2e-tests
