name: "E2E Test"
description: "Reusable e2e test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: "24.x"

    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: pnpm install
    - shell: bash
      run: pnpm e2e-tests
