name: "E2E Test"
description: "Reusable e2e test action"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: the-wireguard-effect
        path: /tmp/the-wireguard-effect

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: "24.x"

    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

    - shell: bash
      run: tar -xvf /tmp/the-wireguard-effect/the-wireguard-effect.tar
    - shell: bash
      run: pnpm install
    - shell: bash
      run: pnpm e2e-tests
