name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'schedule' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: ./.github/actions/build

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/e2e

  linux-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux

  macos-intel-test:
    runs-on: macos-13
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-intel

  macos-apple-silicon-test:
    runs-on: macos-14
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-apple-silicon

  windows-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows

  windows-wsl2-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-wsl2
