name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/common-setup
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            submodules/wireguard-go/go.sum
      - run: pnpm check
      - run: pnpm build
      - run: pnpm test
