name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

# https://github.com/orgs/community/discussions/45140#discussioncomment-7740994
concurrency:
  cancel-in-progress: false
  group: ${{ ((endsWith(github.run_number, '0') || endsWith(github.run_number, '3') || endsWith(github.run_number, '6') || endsWith(github.run_number, '9'))) && '0' || (((endsWith(github.run_number, '1') || endsWith(github.run_number, '4') || endsWith(github.run_number, '7'))) && '1' || '2') }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: ./.github/actions/build

  e2e-test:
    # FIXME: Enable when ready
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/e2e

  linux-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux

  macos-intel-test:
    runs-on: macos-13
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-intel

  macos-apple-silicon-test:
    runs-on: macos-14
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-apple-silicon

  windows-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows

  windows-wsl2-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-wsl2
