name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  macos-service-identifier: "1"
  linux-service-identifier1: "2"
  linux-service-identifier2: "3"
  windows-service-identifier: "4"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/common-setup
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            submodules/wireguard-go/go.sum
      - run: pnpm build

  linux-service1:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install wireguard
      - run: python3 -m http.server &
      - run: ip link show
      - run: ifconfig
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}

  linux-service2:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.linux-service-identifier2 }}

  windows-service:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.windows-service-identifier }}

  macos-service:
    needs: [build]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.macos-service-identifier }}

  clients:
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install wireguard
      - id: connect1
        uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}
      - id: test1
        if: ${{ always()}}
        run: curl http://${{steps.connect1.outputs.service-address}}:8000
      # - id: connect2
      #   uses: ./.github/actions/workflow-level-service/connect
      #   with:
      #     service-identifier: ${{ env.linux-service-identifier2 }}
      # - id: connect3
      #   uses: ./.github/actions/workflow-level-service/connect
      #   with:
      #     service-identifier: ${{ env.windows-service-identifier }}
      # - id: connect4
      #   uses: ./.github/actions/workflow-level-service/connect
      #   with:
      #     service-identifier: ${{ env.macos-service-identifier }}

  stop-services:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [clients]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.linux-service-identifier2 }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.windows-service-identifier }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.macos-service-identifier }}

  # https://github.com/orgs/community/discussions/26822
  pr-can-merge:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [clients, linux-service1, linux-service2, windows-service, macos-service]
    steps:
      - run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
