name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'schedule' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: ./.github/actions/build

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/e2e

  linux-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux

  macos-intel-test:
    runs-on: macos-13
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-intel

  macos-apple-silicon-test:
    runs-on: macos-14
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mac-apple-silicon

  freebsd-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: the-wireguard-effect
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg install -y sudo node npm bash
            npm -v
            node -v
            npm install -g pnpm
          run: |
            pnpm install
            chmod +x ./src/*
            kldload linux64
            pnpm test

  openbsd-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: the-wireguard-effect
      - uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg_add sudo-1.9.15.5 node bash
            npm -v
            node -v
            npm install -g pnpm
          run: |
            pnpm install
            chmod +x ./src/*
            pnpm test

  windows-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows

  windows-wsl2-test:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-wsl2
