name: Publish

on:
  release:
    types: [published]

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y wireguard

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-go@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: "Install dependencies with pnpm"
        shell: bash
        run: pnpm install

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"
      - run: pnpm check
      - run: pnpm build
      - run: pnpm test
      - run: pnpm publish --no-git-checks --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm init -y --scope ${{ github.repository_owner }}
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
