name: Publish

on:
  release:
    types: [published]

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # Setup go and node
      - uses: actions/setup-go@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"

      # Setup pnpm and pnpm cache
      - uses: pnpm/action-setup@v4

      # Install build deps
      - shell: bash
        run: sudo apt-get -y install mingw-w64 libarchive-tools clang cmake libxml2-dev imagemagick librsvg2-bin openresolv

      # Check, lint, and build
      - shell: bash
        run: pnpm install
      - shell: bash
        run: pnpm check
      - shell: bash
        run: pnpm lint
      - shell: bash
        run: pnpm circular
      - shell: bash
        run: pnpm build

      # Publish to npm
      - run: pnpm publish --no-git-checks --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm init -y --scope ${{ github.repository_owner }}
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
